# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u670d\u52a1\u5668ip')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('fromip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u6765\u6e90ip')),
                ('indoorip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u5185\u90e8ip')),
                ('userlogintime', models.CharField(default='NULL', max_length=30, verbose_name='\u767b\u5f55\u65f6\u95f4')),
                ('useruptime', models.CharField(default='NULL', max_length=15, verbose_name='\u5728\u7ebf\u65f6\u957f')),
            ],
        ),
        migrations.CreateModel(
            name='RadGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('groupname', models.CharField(default='vpnuser', max_length=20, verbose_name='\u7ec4')),
                ('priority', models.IntegerField(default=1, verbose_name='priority')),
            ],
        ),
        migrations.CreateModel(
            name='RadUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('attribute', models.CharField(default='Cleartext-Password', max_length=19, verbose_name='\u8ba4\u8bc1')),
                ('op', models.CharField(default=':=', max_length=2, verbose_name='\u8ba4\u8bc12')),
                ('value', models.CharField(default='NeusoftOpenVpn.Nss@A3-200OK', max_length=64, verbose_name='\u5bc6\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u670d\u52a1\u5668ip')),
                ('serverdomain', models.CharField(default='NULL', max_length=30, verbose_name='\u670d\u52a1\u5668\u57df\u540d')),
                ('enable', models.BooleanField(default=True, verbose_name='\u542f\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('validserver', models.IntegerField(default='NULL', verbose_name='\u5141\u8bb8\u5217\u8868')),
                ('isfreeze', models.BooleanField(default=True, verbose_name='\u51bb\u7ed3')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u670d\u52a1\u5668ip')),
                ('username', models.CharField(default='NULL', max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('fromip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u6765\u6e90ip')),
                ('indoorip', models.GenericIPAddressField(protocol='ipv4', verbose_name='\u5185\u90e8ip')),
                ('userlogintime', models.CharField(default='NULL', max_length=30, verbose_name='\u767b\u5f55\u65f6\u95f4')),
                ('userlogouttime', models.CharField(default='NULL', max_length=30, verbose_name='\u4e0b\u7ebf\u65f6\u95f4')),
                ('useruptime', models.CharField(default='NULL', max_length=10, verbose_name='\u5728\u7ebf\u65f6\u957f')),
            ],
        ),
    ]
