# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='useruptime',
            field=models.CharField(default='NULL', max_length=15, verbose_name='\u5728\u7ebf\u65f6\u957f'),
        ),
    ]
