# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_auto_20170416_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='userlogintime',
            field=models.CharField(default='NULL', max_length=50, verbose_name='\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='userlogouttime',
            field=models.CharField(default='NULL', max_length=50, verbose_name='\u4e0b\u7ebf\u65f6\u95f4'),
        ),
    ]
