# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0003_auto_20170416_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(blank=True, max_length=253, null=True)),
                ('groupname', models.CharField(blank=True, max_length=253, null=True)),
                ('realm', models.CharField(blank=True, max_length=64, null=True)),
                ('nasipaddress', models.GenericIPAddressField()),
                ('nasportid', models.CharField(blank=True, max_length=15, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctsessiontime', models.BigIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=50, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=50, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(blank=True, max_length=50, null=True)),
                ('callingstationid', models.CharField(blank=True, max_length=50, null=True)),
                ('acctterminatecause', models.CharField(blank=True, max_length=32, null=True)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('xascendsessionsvrkey', models.CharField(blank=True, max_length=10, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('acctstartdelay', models.IntegerField(blank=True, null=True)),
                ('acctstopdelay', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadGroupCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name='RadGroupReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name='RadPostAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=253)),
                ('password', models.CharField(blank=True, db_column='pass', max_length=128, null=True)),
                ('reply', models.CharField(blank=True, max_length=32, null=True)),
                ('calledstationid', models.CharField(blank=True, max_length=50, null=True)),
                ('callingstationid', models.CharField(blank=True, max_length=50, null=True)),
                ('authdate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
