# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_auto_20170416_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
        ),
    ]
