# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0005_radreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raduserlist',
            name='attribute',
            field=models.CharField(default='Crypt-Password', max_length=19, verbose_name='\u8ba4\u8bc1'),
        ),
    ]
