# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0007_nas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='inputoctets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='outputoctets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='userlogintime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='userlogouttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='useruptime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
